"""Market scanner table renderer.

Displays scanner results as a color-coded table. Includes a Refresh
button to re-run the scan, and a symbol selector that updates
`st.session_state.symbol` so the dashboard chart can later load the
chosen coin.
"""

from __future__ import annotations

import pandas as pd
import streamlit as st

from app.components.common import WATCHLIST_SYMBOLS


def _color_signal(value) -> str:
    """Green for BUY, yellow for HOLD, red for SELL."""
    if isinstance(value, str):
        upper = value.upper()
        if upper == "BUY":
            return "color: #00c853; font-weight: 600;"
        if upper == "HOLD":
            return "color: #ffc107; font-weight: 600;"
        if upper == "SELL":
            return "color: #ff1744; font-weight: 600;"
    return ""


def render_scanner_table(results: list[dict]) -> None:
    """Render scanner results with refresh control, color-coded table, and symbol selection."""
    if not results:
        st.warning("No scanner results available. Check the Binance connection and try again.")
        return

    # --- Scanner controls: refresh + info ---
    control_cols = st.columns([1, 3])
    with control_cols[0]:
        if st.button("🔄 Refresh Scanner", width="stretch"):
            st.rerun()
    with control_cols[1]:
        st.caption(
            f"Scanning {len(WATCHLIST_SYMBOLS)} symbols from the shared watchlist — "
            "signals are generated by the same strategy the trading bot uses."
        )

    st.divider()

    # --- Build the DataFrame with friendly display names ---
    df = pd.DataFrame(results).rename(
        columns={
            "symbol": "Symbol",
            "price": "Price",
            "signal": "Signal",
            "rsi": "RSI",
            "ema_trend": "EMA Trend",
            "score": "Score",
            "recommendation": "Recommendation",
        }
    )

    # Color the Signal column (BUY green / HOLD yellow / SELL red)
    styler = df.style.map(_color_signal, subset=["Signal"])

    # Native formatting via the Styler (na_rep displays "—" for missing values)
    styler = styler.format(
        {"Price": "{:,.6f}", "RSI": "{:.1f}", "Score": "{:.1f}"},
        na_rep="—",
    )

    # --- Table with fixed height + vertical scrolling ---
    st.dataframe(
        styler,
        hide_index=True,
        width="stretch",
        height=450,
    )

    st.divider()

    # --- Symbol selection (sets the active dashboard symbol) ---
    st.markdown("#### Select a symbol for the dashboard")
    sel_col, btn_col = st.columns([3, 1])
    with sel_col:
        selected = st.selectbox(
            "Symbol",
            options=[row["symbol"] for row in results],
            label_visibility="collapsed",
            key="scanner_symbol_select",
        )
    with btn_col:
        if st.button("Load on Dashboard", width="stretch"):
            st.session_state.symbol = selected
            st.rerun()